name: Read Hello File

on:
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display hello.txt
        run: cat hello.txt
